Updated phpunit version
In PHPUnit version 3.7.13 the command-line run results in an error
due to a change in PHP_Timer usage (static vs instantiated).

Fatal error: Call to undefined method PHPUnit_TextUI_ResultPrinter::timeSinceStartOfRequest() in vendor/phpunit/php-timer/PHP/Timer.php on line 150